gnb_id: 411
ran_node_name: cu_cp_01

cu_cp:
  amf:
    addr: 10.53.1.2
    bind_addr: 10.53.1.1
    bind_interface: auto
    supported_tracking_areas: # List of tracking areas supported by this AMF. Note that the first PLMN is used for the Global RAN Node ID
      - tac: 7
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1
  f1ap:
    bind_addr: 127.0.10.1
  inactivity_timer: 7200

cu_up:
  nru:
    bind_addr: 127.0.10.1
    udp_max_rx_msgs: 256

e2:
  enable_cu_cp_e2: true
  enable_cu_up_e2: true
  e2sm_kpm_enabled: true            # Enable KPM service module
  e2sm_rc_enabled: true
  addr: 10.0.2.10                   # RIC IP address
  bind_addr: 10.0.2.1               # A local IP that the E2 agent binds to for traffic from the RIC. ONLY required if running the RIC on a separate machine. 
  port: 36421                       # RIC port

log:
  filename: /tmp/cu1.log
  all_level: info # debug | info | warning
  cu_level: debug                     # Optional TEXT (warning). Sets the CU log level. 
  rrc_level: debug                    # Optional TEXT (warning). Sets RRC log level.
  sdap_level: warning                   # Optional TEXT (warning). Sets SDAP log level.
  ngap_level: warning                   # Optional TEXT (warning). Sets NGAP log level.
  gtpu_level: warning                   # Optional TEXT (warning). Sets GTPU log level.
  f1ap_level: warning                   # Optional TEXT (warning). Sets F1AP log level.
  sec_level: warning                    # Optional TEXT (warning). Sets security functions level.
  lib_level: warning                    # Optional TEXT (warning). Sets generic log level.
  config_level: none                    # Optional TEXT (none). Sets the config log level.
  metrics_level: none                   # Optional TEXT (none). Sets the metrics log level.
  tracing_filename:                     # Optional TEXT. Set to a valid file name to enable tracing log.
  f1ap_json_enabled: false              # Optional BOOLEAN (false). Enables the JSON logging of F1AP PDUs.
  hex_max_size: 0                       # Optional UINT (0). Sets maximum number of bytes to print for hex messages. Supported: [0 - 1024]
  f1u_level: warning                    # Optional TEXT (warning). Sets F1u log level.
  e2ap_level: debug                   # Optional TEXT (warning). Sets E2AP log level.
  pdcp_level: warning                   # Optional TEXT (warning). Sets PDCP log level.

pcap:
  ngap_enable: false
  ngap_filename: /tmp/cu_ngap.pcap

